# Generated by Django 2.2.6 on 2022-07-12 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinurl_list',
            name='meeting_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Meeting_details'),
        ),
    ]
