# Generated by Django 2.2.6 on 2022-07-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220712_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinurl_list',
            name='meeting_details',
        ),
    ]
