# Generated by Django 2.2.6 on 2022-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_joinurl_list_meeting_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinurl_list',
            name='meeting_list',
        ),
        migrations.AddField(
            model_name='joinurl_list',
            name='password',
            field=models.CharField(default='p', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinurl_list',
            name='start_time',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinurl_list',
            name='join_url',
            field=models.CharField(max_length=250),
        ),
    ]
