# Generated by Django 2.2.6 on 2022-07-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_joinurl_list_meeting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinurl_list',
            old_name='meeting_id',
            new_name='description',
        ),
    ]
