# Generated by Django 2.2.6 on 2022-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220712_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinurl_list',
            name='description',
            field=models.CharField(max_length=350),
        ),
    ]
